### ISSUE TITLE
"Unknown action - The action 'show' could not be found for Store::OrderController"

### ISSUE THREAD

**Issue by dburr** [remear/potionstore#4]
Trying to get your fork of potionstore going on a CentOS 6 server.  Have installed all the bundles as specified by the Gemfile.  Have set up my Paypal sandbox username, password and signature.  At first, "buying" a product using paypal appears to work fine (I get redirected to paypal, sign in with my sandbox buyer account, agree to purchase the item), and I get redirected back to my site (http://store.donaldburr.com:3000/store/order/confirm_paypal?token=EC-1CJ926261X160031C&PayerID=U7DP8PAUHBPN2); however instead of a "order complete' (or whatever I'm supposed to get), I get the error message "Unknown action - The action 'show' could not be found for Store::OrderController" and in my terminal window (then one I'm running "rails s" from) I get the following:

Redirected to https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-1CJ926261X160031C
Completed 302 Found in 1336ms (ActiveRecord: 59.7ms)

Started GET "/store/order/confirm_paypal?token=EC-1CJ926261X160031C&PayerID=U7DP8PAUHBPN2" for 68.99.127.102 at Fri May 11 14:52:17 -0700 2012

AbstractController::ActionNotFound (The action 'show' could not be found for Store::OrderController):
  actionpack (3.2.2) lib/abstract_controller/base.rb:116:in `process'
  actionpack (3.2.2) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.2) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.2) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.2) lib/action_controller/metal.rb:246:in `action'
  actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:67:in`call'
  actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:67:in `dispatch'
  actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:30:in`call'
  journey (1.0.3) lib/journey/router.rb:68:in `call'
  journey (1.0.3) lib/journey/router.rb:56:in`each'
  journey (1.0.3) lib/journey/router.rb:56:in `call'
  actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:594:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in`call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.2) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:443:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in`call'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `_run__899149591__call__4__callbacks'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in`send'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.2) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.2) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.2) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/reloader.rb:65:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.2) lib/rails/rack/logger.rb:26:in`call_app'
  railties (3.2.2) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/static.rb:61:in `call'
  railties (3.2.2) lib/rails/engine.rb:479:in`call'
  railties (3.2.2) lib/rails/application.rb:220:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in`call'
  railties (3.2.2) lib/rails/rack/log_tailer.rb:14:in `call'
  rack (1.4.1) lib/rack/handler/webrick.rb:59:in`service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
  /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in`start'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:95:in`start'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in`start'
  /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:82:in`start'
  rack (1.4.1) lib/rack/handler/webrick.rb:13:in `run'
  rack (1.4.1) lib/rack/server.rb:265:in`start'
  railties (3.2.2) lib/rails/commands/server.rb:70:in `start'
  railties (3.2.2) lib/rails/commands.rb:55
  railties (3.2.2) lib/rails/commands.rb:50:in`tap'
  railties (3.2.2) lib/rails/commands.rb:50
  script/rails:6:in `require'
  script/rails:6

  Rendered /usr/lib64/ruby/gems/1.8/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/unknown_action.erb within rescues/layout (0.3ms)

Any ideas?  Unfortunately I'm still a Ruby/rails neophyte.  Thanks!

**Comment by remear** [comment]
I'll look into this when I get a good block of time. Keep in mind that I have a huge group of commits I'm working to clean up and push to my branch. This batch fixes a lot of issues that are still in the version you have.

**Comment by remear** [comment]
@dburr I've pushed all of my changes. You'll probably want to delete your old version and clone mine again since I rewrote some history.
